# title: Kibtia Chowdhury
logo: /assets/img/kibtia.png
description: Research Associate at ASRC, PolyU
# show_downloads: true
# theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
